name: dummy-test
on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  split-message:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Branch
      id: checkout-branch-from-master
      uses: actions/checkout@v2
      
    - name: Get commit message
      id: commit_message
      run: |
        commit_message=$(git log --format=%B)
        export message=${commit_message}
        echo $message

    - name: Split commit message
      id: split_message
      run: |
        IFS='---'
        export message=${{ steps.commit_message.outputs.message }}
        tr -s ' ' '\---' <<< "$message"
        read -r -a parts <<< "$(tr -s ' ' '\---' <<< "$message")"
        export Environment=${parts[0]}
        export AppCustomID=${parts[1]}
        export CommitMessage=${parts[2]}
        echo $Environment
        echo $AppCustomID
        echo $CommitMessage
