name: Get Commit Message
on: [push]

jobs:
  get-and-split-commit-message:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Commit Message
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})
          echo "Commit message: $COMMIT_MESSAGE"
      - name: Split Commit Message
        run: |
          IFS='---' read -ra SPLIT_MESSAGE <<< "$COMMIT_MESSAGE"
          for i in "${SPLIT_MESSAGE[@]}"; do
            echo "Part: $i"
          done
