name: Get Commit Message
on: [push]

jobs:
  get-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Get Commit Message
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})
          echo "Commit message: $COMMIT_MESSAGE"
      - name: Split Commit Message
        run: |
          IFS='---' read -ra SPLIT_MESSAGE <<< "$COMMIT_MESSAGE"
          for i in "${SPLIT_MESSAGE[@]}"; do
            echo "Part: $i"
          done

      # - name: Display Commit Message
      #   id: display_message
      #   run: echo "Commit Message: ${{ steps.commit_message.outputs.message }}"

      # - name: Split Commit Message
      #   id: split_message
      #   run: echo "::set-output name=split_message::$(echo '${{ steps.commit_message.outputs.message }}' | awk -v RS='---' 'NR==1{print}')"

      # - name: Display Split Message
      #   run: echo "Split Message: ${{ steps.split_message.outputs.split_message }}"
