name: Get commit message and split

on:
  push:
    branches:
      - main

jobs:
  get-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Print changed file path
        run: |
          current_commit_sha=$(git rev-parse HEAD)
          previous_commit_sha=$(git rev-parse HEAD~1)
          changed_file_path=$(git diff --name-only $previous_commit_sha $current_commit_sha)
          echo "Changed file path: $changed_file_path"
          
      - name: Split commit message
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          commit_message_parts=$(echo "${{ github.event.head_commit.message }}" | tr -s '||' "\n")
          echo "Commit message parts:"
          for part in "${commit_message_parts[@]}"
          do
            echo "$part"
          done
