name: Get commit message and split

on:
  push:
    branches:
      - main

jobs:
  get-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Get commit message
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.head_commit.ref }}
          
      - name: Get changed files
        uses: actions/changed-files@v2
        with:
          # Only get the changed files in the main branch.
          branch: main

      - name: Print changed file path
        run: |
          echo "The changed file path is: ${{ steps.get-changed-files.outputs.changed_files[0] }}"
          
      - name: Split commit message
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          commit_message_parts=$(echo "${{ github.event.head_commit.message }}" | tr -s '||' "\n")
          echo "Commit message parts:"
          for part in "${commit_message_parts[@]}"
          do
            echo "$part"
          done
