name: Get commit message and split

on:
  push:
    branches:
      - main

jobs:
  get-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Get commit message
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.head_commit.ref }}
          
      - name: List Changed Files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | while read -r file; do
            echo "Changed File: $file"
          done
          
      - name: Split commit message
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          commit_message_parts=$(echo "${{ github.event.head_commit.message }}" | tr -s '||' "\n")
          echo "Commit message parts:"
          for part in "${commit_message_parts[@]}"
          do
            echo "$part"
          done
