name: dummy-test
on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Branch
      id: checkout-branch-from-master
      uses: actions/checkout@v2
      
    - name: Get commit message
      id: commit_message
      run: |
        commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
        echo "::outputs::message=${commit_message}"

    - name: Split commit message
      id: split_message
      run: |
        IFS='---'
        commit_message=$(echo "$commit_message")
        if [ -n "$commit_message" ]; then
          read -r -a parts <<< "$commit_message"
          echo "::outputs::Environment=${parts[0]}"
          echo "::outputs::App Custom ID=${parts[1]}"
          echo "::outputs::Commit Message=${parts[2]}"
        fi
