name: Get and Split Commit Message

on:
  push:
    branches:
      - main 
jobs:
  get-and-split-commit-message:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Commit Message
        id: commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"

      # - name: Display Commit Message
      #   id: display_message
      #   run: echo "Commit Message: ${{ steps.commit_message.outputs.message }}"

      # - name: Split Commit Message
      #   id: split_message
      #   run: echo "::set-output name=split_message::$(echo '${{ steps.commit_message.outputs.message }}' | awk -v RS='---' 'NR==1{print}')"

      # - name: Display Split Message
      #   run: echo "Split Message: ${{ steps.split_message.outputs.split_message }}"
