name: dummy-test

on:
  pull_request:
  release:
    types:
      - edited
      - created
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Echo Test
      id: echo-test
      run: |
        echo :: Test
